### ISSUE TITLE
Publications and citation of nonlinearTseries

### ISSUE THREAD

**Issue by mxochicale** [constantino-garcia/nonlinearTseries#1]
Dear Constantino,

I am wondering if you are aware of publications that used nonlinearTseries.
Can you share those references? It would be helpful to add a section in the 
README.md called "portfolio of publications used nonlinearTseries.
Additionally, it would be useful that you provide information about 
the citation of nonlinearTseries package. Something like this: 
```
  @Manual{,
    title = {nonlinearTseries: Nonlinear Time Series Analysis},
    author = {Constantino A. Garcia and Gunther Sawitzki},
    year = {2016},
    note = {R package version 0.2.4 --- For new features, see the 'Changelog' file (in the package source)},
 }
```

NB. I can pull a request for the README if you update the previous information.

Kind regards,
Miguel

**Comment by constantino-garcia** [comment]
Dear Miguel,

I am not aware of any publication using nonlinearTseries, so I don't think it makes sense to add the "portfolio" at the moment.

On the other hand, you can get information about how to cite any R package using `citation()`. In the case of nonlinearTseries it would be: `citation('nonlinearTseries')`

Anyway, I would add the citation info to the README.

Kind regards.
