### ISSUE TITLE
package is not installed 

### ISSUE THREAD

**Issue by MoustafaArgus** [constantino-garcia/nonlinearTseries#3]
For some reason which I cannot understand the package cannot be installed. The usual error I get is: 

_Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'htmltools' 0.3.6 is already loaded, but >= 0.4.0 is required
Calls: <Anonymous> ... asNamespace -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'nonlinearTseries'_

**Comment by constantino-garcia** [comment]
It seems you need to update the 'htmltools' package. install.packages("htmltools") should fix the error. Please confirm if this solves your problem.

**Comment by constantino-garcia** [comment]
Closing. Feel free to reopen it if this does not solve your problem.
