### ISSUE TITLE
Changing estimateEmbeddingDim output if no appropriate dimension can be found?

### ISSUE THREAD

**Issue by a-paxton** [constantino-garcia/nonlinearTseries#4]
Hi, there,

Thanks for the incredibly helpful package! I noticed that `estimateEmbeddingDim` returns a `0` when there is no suitable embedding dimension below the chosen maximum. Would it be possible to shift this so that it gives something else (e.g., `NA`) instead? I'd happily submit a PR to address it, if you'd like.

Cheers,
Alex

**Comment by constantino-garcia** [comment]
Yes, that makes sense! Fill free to submit the PR!

**Comment by a-paxton** [comment]
Great—thanks!

**Comment by constantino-garcia** [comment]
Fixed by #5
