### ISSUE TITLE
unable to load package into R

### ISSUE THREAD

**Issue by alisoniles** [constantino-garcia/nonlinearTseries#6]
Hi there, 
I would very much like to check this R package out, but I'm running into trouble with loading it into R on my Mac.  I'm able to install the package into my R library (I've checked that it is there in the '.libPaths()' directory), but when I try to load it into my workspace, it never loads. I've tried in Rgui and and I don't get an error, just the unresponsive wheel banner. In Rstudio, all I get is the following warning, but it remains "running" and basically unresponsive.  

>library(nonlinearTseries)
Registered S3 method overwritten by 'htmlwidgets':
  method           from         
  print.htmlwidget tools:rstudio

What are the other packages 'nonlinearTseries' depends on? Perhaps I need to install those first?

Thank you. 
Any insight you can give would be helpful,
Alison

**Comment by constantino-garcia** [comment]
Hi Alison, 

I cannot reproduce the issue, so it is difficult for me to help. However, you may be try to reinstall 'nonlinearTseries', which should also install all required dependencies (there is probably a better workaround, but without testing this is all I can suggest):
```r
install.packages('nonlinearTseries', dependencies = TRUE)
```
Let me know if this works.
Kind regards
